name: Update image daily

on:
  schedule:
    - cron: "10 0 * * *"
  workflow_dispatch:
    branches: [master]

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run script file
        run: chmod +x ./cron.sh && ./cron.sh
        shell: bash

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.GH_USERNAME }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Build, tag, and push image to GHCR
        env:
          NAME: ip-geo-api
          IMAGE_TAG: ${{ github.sha }}
          USERNAME: ${{ secrets.GH_USERNAME }}
          REGISTRY: ghcr.io/$USERNAME/$NAME
        run: |
          docker build -t $NAME .
          docker tag $NAME $REGISTRY
          docker push $REGISTRY
          docker tag $NAME $REGISTRY:$IMAGE_TAG
          docker push $REGISTRY:$IMAGE_TAG
