name: Update image daily

on:
  schedule:
    - cron: "10 0 * * *"
  workflow_dispatch:
    branches: [master]

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run script file
        run: chmod +x ./cron.sh && ./cron.sh
        shell: bash

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.TOKEN }}

      - name: Build, tag, and push image to GHCR
        env:
          NAME: ip-geo-api
          IMAGE_TAG: ${{ github.sha }}
          USERNAME: ${{ secrets.USERNAME }}
        run: |
          docker build -t $NAME .
          docker tag $NAME $USERNAME/$NAME
          docker push $USERNAME/$NAME
